# For a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "resume"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = ["Stephen Xu <https://stuxf.dev>", "Jake Wang <wxx9248@wxx9248.top>"]
license = "Unlicense"
description = "A simple, standard resume, designed to work well with ATS."
repository = ""
keywords = ["cv", "resume", "ATS"]
categories = ["cv"]
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
